
# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/circleci-docker-artifactory

    steps:
      - checkout
      - setup_remote_docker

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      # Install JFrog CLI
      - run: curl -fL https://getcli.jfrog.io | sh
      # Configure Artifactory instance with JFrog CLI
      - run: ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_PASSWORD --interactive false
      # Login to Artifactory docker registry
      - run: docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_PASSWORD $ARTIFACTORY_DOCKER_REPOSITORY
      # Run NPM install command to pull dependency from Artifactory NPM registry
      - run: ./jfrog rt npmi $NPM_DEV_REPO --build-name=$CIRCLE_JOB --build-number=$CIRCLE_BUILD_NUM
      # Test NPM package
      - run: npm test
      # Run NPM publish command to publish created NPM package to Artifactory NPM registry
      - run: ./jfrog rt npmp $NPM_DEV_REPO --build-name=$CIRCLE_JOB --build-number=$CIRCLE_BUILD_NUM
      # Capture environment variables for build information
      - run: ./jfrog rt bce $CIRCLE_JOB $CIRCLE_BUILD_NUM
      # Publish build information to Artifactory
      - run: ./jfrog rt bp $CIRCLE_JOB $CIRCLE_BUILD_NUM
      # Scan Build through JFrog Xray (Optional)
      - run: ./jfrog rt bs $CIRCLE_JOB $CIRCLE_BUILD_NUM
      # Promote build to Staging
      - run: ./jfrog rt bpr $CIRCLE_JOB $CIRCLE_BUILD_NUM $NPM_STAGE_REPO --status="Staged" --copy=true
      # Promote build to Production
      - run: ./jfrog rt bpr $CIRCLE_JOB $CIRCLE_BUILD_NUM $NPM_PROD_REPO --status="Promoting to Prod" --copy=true
      # Distribute build to Bintray (This step requires JFrog Bintray. You can comment it if not using Bintray)
      - run: ./jfrog rt bd $CIRCLE_JOB $CIRCLE_BUILD_NUM $NPM_DISTRIBUTION_REPO
